java_test(
    name = "javatest",
    srcs = [
        "ExampleTest.java",
    ],
    test_class = "com.github.sjoerdvisscher.coverage.ExampleTest",
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java:javaunittest",
        "@maven//:junit_junit",
    ],
)