java_test(
    name = "ExampleTest",
    srcs = [
        "ExampleTest.java",
    ],
    test_class = "com.github.liucijus.coverage.javaunittest.ExampleTest",
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/github/liucijus/coverage/javaunittest",
        "@maven//:junit_junit",
    ],
)
