load("@io_bazel_rules_scala//scala:scala.bzl", "scala_test")

scala_test(
    name = "scalatest",
    srcs = [
        "ExampleSpec.scala",
    ],
    deps = ["//src/main/scala/com/github/liucijus/coverage/scalatest"],
)
